# Generated by Django 4.2.2 on 2023-10-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID USUARIO')),
                ('user' , models.CharField(max_length=20,verbose_name = "Nombre Usuario")),
                ('password' , models.CharField(max_length=20, verbose_name = "Contraseña Usuario")),
                ('nombre' , models.CharField(max_length=20, verbose_name = "Nombre de la Persona")),
                ('correo' , models.CharField(max_length=50, verbose_name = "Correo de la Persona")),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('idViaje', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID VIAJE')),
                ('hora', models.IntegerField(verbose_name='Hora de inicio del Viaje')),
                ('costo', models.CharField(max_length=5, verbose_name='Costo del Viaje')),
                ('capacidad', models.CharField(max_length=1, verbose_name='Capacidad de Pasajeros')),
            ],
        ),
    ]

    
