# Generated by Django 4.2.2 on 2023-10-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID USUARIO')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de Usuario')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Contraseña Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('idViaje', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID VIAJE')),
                ('hora', models.IntegerField(verbose_name='Hora de inicio del Viaje')),
                ('costo', models.CharField(max_length=5, verbose_name='Costo del Viaje')),
                ('capacidad', models.CharField(max_length=1, verbose_name='Capacidad de Pasajeros')),
            ],
        ),
    ]
