# Generated by Django 4.2.2 on 2023-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='capacidad',
            field=models.IntegerField(max_length=1, verbose_name='Capacidad de Pasajeros'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='costo',
            field=models.IntegerField(max_length=5, verbose_name='Costo del Viaje'),
        ),
    ]
