# Generated by Django 4.2.2 on 2023-11-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_username_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
