# Generated by Django 4.2.7 on 2023-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_user_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='patente',
            field=models.CharField(max_length=10, verbose_name='patente'),
        ),
    ]
